#!/usr/bin/env python3
"""Build every derived artifact of the HLM5 paper from the single-column master.

The one authored file is ``paper/hlm5-paper.tex``. Everything else is derived
and regenerated by this script so the artifacts never drift from the master:

  1. ``hlm5-paper-twocol.tex``  -- two-column variant (see make_twocol.py)
  2. ``hlm5-paper.pdf``         -- single-column PDF   (tectonic)
  3. ``hlm5-paper-twocol.pdf``  -- two-column PDF      (tectonic)
  4. ``hlm5-paper.docx``        -- Word conversion     (pypandoc; --skip-docx to skip)
  5. ``hlm5-paper-overleaf.zip``-- both .tex + referenced figures (Overleaf drop-in)
  6. ``arxiv/hlm5-paper-arxiv.zip`` -- single master .tex + its figures only
                                       (arXiv AutoTeX wants exactly one top-level tex)

Requirements
------------
* tectonic (https://tectonic-typesetting.github.io/) on PATH, or pass
  ``--tectonic /path/to/tectonic``. Install: ``cargo install tectonic`` or grab a
  release binary; on first run it fetches the TeX support bundle over the network.
* pypandoc + pandoc for the .docx step: ``pip install pypandoc-binary``.
  Use ``--skip-docx`` on boxes without it.

Usage
-----
    python paper/build.py                       # tectonic from PATH
    python paper/build.py --tectonic C:/…/tectonic.exe
    python paper/build.py --skip-docx
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
MASTER = os.path.join(HERE, "hlm5-paper.tex")
TWOCOL = os.path.join(HERE, "hlm5-paper-twocol.tex")
ARXIV_DIR = os.path.join(HERE, "arxiv")

_INCLUDE_RE = re.compile(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}")


def _referenced_figures(*tex_paths):
    """Ordered, de-duplicated list of figure paths referenced by the given .tex."""
    seen, out = set(), []
    for tex in tex_paths:
        src = open(tex, encoding="utf-8").read()
        for rel in _INCLUDE_RE.findall(src):
            rel = rel if rel.lower().endswith(".pdf") else rel + ".pdf"
            if rel not in seen:
                seen.add(rel)
                out.append(rel)
    return out


def step_twocol():
    print("== [1/6] two-column variant ==")
    import make_twocol  # local module (paper/ is on sys.path)
    make_twocol.main(["--input", MASTER, "--output", TWOCOL])


def step_pdf(tectonic, tex):
    name = os.path.basename(tex)
    print(f"== compile {name} ==")
    cmd = [tectonic, "--outdir", HERE, "--keep-logs", tex]
    proc = subprocess.run(cmd, cwd=HERE)
    if proc.returncode != 0:
        raise SystemExit(f"build: tectonic failed on {name} (exit {proc.returncode})")
    pdf = os.path.splitext(tex)[0] + ".pdf"
    print(f"   wrote {pdf} ({os.path.getsize(pdf):,} bytes)")
    return pdf


def step_docx():
    print("== [4/6] docx (pypandoc) ==")
    try:
        import pypandoc
    except ImportError:
        print("   pypandoc not installed; skipping (rerun with --skip-docx to silence)")
        return None
    out = os.path.join(HERE, "hlm5-paper.docx")
    cwd = os.getcwd()
    os.chdir(HERE)  # so --resource-path=. resolves figures/
    try:
        pypandoc.convert_file(
            "hlm5-paper.tex", "docx", outputfile=out,
            extra_args=["--standalone", "--resource-path=."],
        )
    finally:
        os.chdir(cwd)
    print(f"   wrote {out} ({os.path.getsize(out):,} bytes)")
    return out


def _write_zip(zip_path, members):
    os.makedirs(os.path.dirname(zip_path), exist_ok=True)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for abspath, arcname in members:
            z.write(abspath, arcname)
    print(f"   wrote {zip_path} ({len(members)} entries, {os.path.getsize(zip_path):,} bytes)")


def step_overleaf():
    print("== [5/6] Overleaf zip (both .tex + figures) ==")
    figs = _referenced_figures(MASTER, TWOCOL)
    members = [(MASTER, "hlm5-paper.tex"), (TWOCOL, "hlm5-paper-twocol.tex")]
    members += [(os.path.join(HERE, f), f) for f in figs]
    _write_zip(os.path.join(HERE, "hlm5-paper-overleaf.zip"), members)


def step_arxiv():
    print("== [6/6] arXiv zip (single master .tex + figures) ==")
    figs = _referenced_figures(MASTER)  # master only -- arXiv wants one top-level tex
    members = [(MASTER, "hlm5-paper.tex")]
    members += [(os.path.join(HERE, f), f) for f in figs]
    _write_zip(os.path.join(ARXIV_DIR, "hlm5-paper-arxiv.zip"), members)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tectonic", default="tectonic",
                    help="path to the tectonic binary (default: tectonic on PATH)")
    ap.add_argument("--skip-docx", action="store_true", help="skip the .docx conversion")
    args = ap.parse_args(argv)

    if HERE not in sys.path:
        sys.path.insert(0, HERE)

    if not (os.path.isabs(args.tectonic) or shutil.which(args.tectonic)):
        raise SystemExit(
            f"build: tectonic not found ('{args.tectonic}'). Install it or pass --tectonic PATH."
        )

    step_twocol()
    step_pdf(args.tectonic, MASTER)
    step_pdf(args.tectonic, TWOCOL)
    if args.skip_docx:
        print("== [4/6] docx skipped (--skip-docx) ==")
    else:
        step_docx()
    step_overleaf()
    step_arxiv()
    print("\nAll artifacts regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
